caso de uso cadastro de campanha para análise :)
Faz-um-bem/backend pull request #3
Opened 2021-07-24 07:00 UTC by jotasv

2021-07-29 01:28 UTC, pedrodeandrade requested changes

2021-07-29 01:28 UTC, pedrodeandrade commented on app/Controllers/Http/Campaign/CreateCampaignController.js
> +    const result = await this.useCase.execute(campaignData);
Tratar erro caso instituição não exista

2021-07-29 01:28 UTC, pedrodeandrade commented on app/Controllers/RequestModels/Campaign/CreateCampaignRequestModel.js
> +    this.address_longitude = createCampaignRequestData.address_longitude;
Receber ID da instituição

2021-07-29 01:28 UTC, pedrodeandrade commented on database/migrations/1626326821344_campaign_schema.js
> +      table.timestamps();
Criar chave estrangeira para relacionar com a tabela "institutions"

2021-07-29 01:28 UTC, pedrodeandrade commented on routes/Campaign/index.js
> +      .post('/campaign', `${this.controllersPath}/Campaign/CreateCampaignController.handle`)
Receber ID da instituição pela url

2021-07-29 01:58 UTC, pedrodeandrade requested changes

2021-07-29 01:58 UTC, pedrodeandrade commented on app/UseCases/Campaign/CreateCampaignUseCase.js
> +    const campaign = await this.campaignModel.create(
Validar existência da instituição e retorna erro caso não exista

2021-08-03 03:37 UTC, jotasv commented on app/UseCases/Campaign/CreateCampaignUseCase.js
> +    const campaign = await this.campaignModel.create(
A parte de validar se a instituição existe está feita, porém ao ocorrer erro, a mensagem de retorno vem vazia.
![Captura de tela 2021-08-03 003621](https://user-images.githubusercontent.com/48728181/127953772-4ee3c2d2-4903-46f3-8ffb-ac5496a79ae6.png)

2021-08-03 03:38 UTC, jotasv commented on routes/Campaign/index.js
> +      .post('/campaign', `${this.controllersPath}/Campaign/CreateCampaignController.handle`)
Recebendo id da instituição pelo corpo da requisição, e não pelo url. (ideia do Wederson)

2021-08-20 01:04 UTC, merged